# Generated by Django 4.1.5 on 2023-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0004_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
